
migrations:
	python manage.py makemigrations
	python manage.py migrate

see_migrations:
	python manage.py sqlmigrate blog 0001

server:
	python manage.py runserver

admin:
	python manage.py createsuperuser